modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="crabcraft"
version="1.0.0"
displayName="CrabCraft"
logoFile="modicon.png"
authors="Ashu"
description='''
Adds crabs, crab loot, and a Crab Claw dash ability.
'''

[[dependencies.crabcraft]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.crabcraft]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.crabcraft]]
modId="geckolib"
type="required"
versionRange="[4.7,)"
ordering="AFTER"
side="BOTH"
